# Generated by Django 5.2.8 on 2026-01-07 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_paciente_atm_paciente_carrillos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='motivo_consulta',
            field=models.TextField(blank=True, null=True),
        ),
    ]
