# Generated by Django 5.2.8 on 2026-01-12 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_paciente_direccion_paciente_ocupacion_paciente_sexo'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='representante',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
