# Generated by Django 5.2.8 on 2026-01-12 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_paciente_representante'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='representante',
            new_name='rep_apellidos',
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_cedula',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_direccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_nombres',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_relacion',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_telefono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='rep_tipo_documento',
            field=models.CharField(default='CEDULA', max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiene_representante',
            field=models.BooleanField(default=False),
        ),
    ]
