# Generated by Django 5.2.8 on 2026-02-02 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_representante_paciente_rep_apellidos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='enfermedad_actual',
            field=models.TextField(blank=True, null=True),
        ),
    ]
